apiVersion: v1
kind: Pod
metadata:
  name: annotations
  metadata:
    labels:
      project: roboshop
      component: frontend
      tier: web
      environment: dev
    annotations:
      description: "this is the annotation for frontend web"
      jenkins: "https://jenkins.com/build/job/roboshop-catalouge/3"
spec:
  containers:
  - name: nginx
    images: nginx  