apiVersion: v1
kind: Pod
metadata:
 name: envar-demo
 labels:
  purpose: demonstrate-environment-variables
spec:
 containers:
 - name: nginx
   image: nginx
   env:
   - name: project
     value: roboshop
   - name: trainer
     value: venu
   - name: duration
     value: 5 months      