apiVersion: v1
kind: ReplicaSet
metadata:
 name: nginx
 # replica set labels
 labels:
  purpose: rs-demo 
  project: roboshop
  app: nginx
spec:
 replicas: 3  
  # These are the labels replica set use to create pod replicas, this should match pod labels
 selector:
  matchLabels:
    purpose: rs-demo
    project: roboshop
    app: nginx
  #this is pod defination  
  template:
    metadata:
      labels:
        purpose: rs-demo
        project: roboshop
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx 